### ISSUE TITLE
Tuesday 18th schedule text overlapping

### ISSUE THREAD

**Issue by yanneves** [ryanoconr/yogs#16]
<img width="155" alt="screenshot 2018-12-17" src="https://user-images.githubusercontent.com/1331877/50059156-0f2a9480-01e8-11e9-8664-f0fc0ea1fe3c.png">

**Comment by ryanoconr** [comment]
Which browser are you using?

**Comment by yanneves** [comment]
Chrome on 13" Macbook Pro. Try resizing viewport to 1280 x 700.

<img width="1141" alt="screenshot 2018-12-17 at 10 56 53" src="https://user-images.githubusercontent.com/1331877/50059342-7ea18380-01ea-11e9-8811-1d92c8c5ca9d.png">

**Comment by yanneves** [comment]
Ah right, ignore that, it was cached CSS - have you considered cache busting since you serve the page static? Happy to spin up a PR to package using Parcel. https://parceljs.org/
