### ISSUE TITLE
css-grid

### ISSUE THREAD

**Issue by Link2Twenty** [ryanoconr/yogs#2]
In my tweet, I mentioned how css-grid might be better than flexbox. I imagine either you had a reason not to use it that I haven't thought about or you don't know about it, or at least enough about it to use it, so I've made a quick demo to hopefully show you the benefits.

http://jsfiddle.net/link2twenty/L5mqzsyn/

Also, this would make it easier to move data around, so you don't need to load all the data twice and just hide half of it.

**Comment by ryanoconr** [comment]
Yeah, I've heard of css-grid but I've never really used it but definitely going to look at switching it from flexbox to css-grid now. Thanks!
